#!/usr/bin/env python3
"""Regenerate the AGENTS.md file-inventory table from front matter.

The inventory table is the consumer agent's map of the wiki: one row per
canonical file with its tier, retrieval-oriented description, and both
freshness dates -- evidence-as-of (the content's age) and last-verified
(when a human or an execution check last looked, SPEC 4.1) -- because a
consumer deciding whether to trust a file needs both, not just the one that
happens to track maintainer activity (taxonomy: "machine-generated by
scripts/sync_manifest.py; never hand-edited"). This script rebuilds the
table between the

    <!-- INVENTORY:START -->
    <!-- INVENTORY:END -->

markers in AGENTS.md from the front matter of every top-level canonical
file. File names render as links, which also makes AGENTS.md the wiki's
link hub for the orphan check.

Rows are sorted in the canonical taxonomy order (SPEC 3); files outside the
taxonomy sort after, alphabetically. Files without parseable front matter
are skipped -- lint reports those separately.

Usage:
    sync_manifest.py WIKI_DIR [--json] [--check]

--check verifies the table is current without writing; exit 1 if stale.
The write mode is idempotent: rerunning on a synced wiki changes nothing.

Exit codes: 0 = in sync (or successfully rewritten); 1 = stale in --check
mode, or an operational error (missing AGENTS.md, missing markers).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from wikilib import (  # noqa: E402
    CANONICAL_ORDER,
    parse_front_matter,
    resolve_wiki_dir,
)

MARKER_RE = re.compile(
    r"(<!--\s*INVENTORY:START\s*-->)(.*?)(<!--\s*INVENTORY:END\s*-->)",
    re.DOTALL,
)
GENERATED_NOTE = "<!-- generated by scripts/sync_manifest.py -- do not hand-edit -->"


def _cell(value: str) -> str:
    """Make a front-matter value safe inside a markdown table cell."""
    if not isinstance(value, str) or not value.strip():
        return "—"
    return value.strip().replace("|", "\\|")


def collect_rows(root: Path) -> list:
    """One row per top-level canonical file with parseable front matter."""
    rows = []
    for path in sorted(root.glob("*.md")):
        if path.name == "AGENTS.md":
            continue
        fm = parse_front_matter(path.read_text(encoding="utf-8"))
        if not (fm.present and fm.closed) or "type" not in fm.data:
            continue
        rows.append({
            "file": path.name,
            "tier": _cell(fm.data.get("type")),
            "description": _cell(fm.data.get("description")),
            # Both dates, not just last-verified: evidence-as-of is about
            # the content's age, last-verified about when a human last
            # looked, and a reader deciding whether to trust a file needs
            # both (SPEC 4.1; taxonomy.md's AGENTS.md section names this
            # table shape explicitly).
            "evidence-as-of": _cell(fm.data.get("evidence-as-of")),
            "last-verified": _cell(fm.data.get("last-verified")),
        })

    def sort_key(row):
        try:
            return (0, CANONICAL_ORDER.index(row["file"]), row["file"])
        except ValueError:
            return (1, 0, row["file"])

    rows.sort(key=sort_key)
    return rows


def render_table(rows: list) -> str:
    lines = [
        GENERATED_NOTE,
        "| File | Tier | Description | Evidence as of | Last verified |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| [{r['file']}]({r['file']}) | {r['tier']} | {r['description']} "
            f"| {r['evidence-as-of']} | {r['last-verified']} |"
        )
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("wiki_dir", help="path to the deployed wiki directory")
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the table is stale; never writes")
    args = parser.parse_args(argv)

    root = resolve_wiki_dir(args.wiki_dir)
    agents = root / "AGENTS.md"

    def report(payload: dict, text: str, code: int) -> int:
        if args.json:
            payload.setdefault("mode", "check" if args.check else "write")
            print(json.dumps(payload, indent=2))
        else:
            print(text)
        return code

    if not agents.is_file():
        return report({"error": "AGENTS.md not found"},
                      f"error: {agents} not found", 1)

    text = agents.read_text(encoding="utf-8")
    m = MARKER_RE.search(text)
    if not m:
        return report(
            {"error": "markers not found"},
            "error: AGENTS.md has no <!-- INVENTORY:START --> / "
            "<!-- INVENTORY:END --> markers",
            1,
        )

    rows = collect_rows(root)
    new_block = f"{m.group(1)}\n{render_table(rows)}\n{m.group(3)}"
    new_text = text[: m.start()] + new_block + text[m.end():]
    in_sync = new_text == text

    if args.check:
        return report(
            {"in_sync": in_sync, "rows": len(rows)},
            "inventory table is current" if in_sync
            else "inventory table is STALE -- run sync_manifest.py to regenerate",
            0 if in_sync else 1,
        )

    if not in_sync:
        agents.write_text(new_text, encoding="utf-8")
    return report(
        {"in_sync": True, "written": not in_sync, "rows": len(rows)},
        f"inventory table {'rewritten' if not in_sync else 'already current'} "
        f"({len(rows)} rows)",
        0,
    )


if __name__ == "__main__":
    sys.exit(main())
